export enum CommonPlatforms {
    Reddit = "reddit",
    Twitter = "twitter",
    Facebook = "facebook",
    Whatsapp = "whatsapp",
    Sms = "sms",
    Linkedin = "linkedin",
    Ark = "ark",
    Youtube = "youtube",
    Amazon = "amazon",
    Twitch = "twitch",
    Radio = "radio",
    Television = "television",
    Bitcoin = "bitcoin",
    Cryptology = "cryptology",
    Telegram = "telegram",
    Slack = "slack",
    Discord = "discord",
    Internet = "internet",
}
